import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { Exam, Submission } from "./types";
import { computeMaxMarks, formatSchemeSummary, getMarkingScheme } from "./markingScheme";

export async function generateStudentReportPdf(exam: Exam, submission: Submission): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage([595, 842]); // A4
  const { width, height } = page.getSize();
  let y = height - 50;

  const drawText = (text: string, x: number, yy: number, size = 10, bold = false, color = rgb(0,0,0)) => {
    page.drawText(text, { x, y: yy, size, font: bold ? fontBold : font, color });
  };

  // Header
  drawText(exam.name.toUpperCase(), 50, y, 16, true);
  y -= 20;
  drawText(`Subject: ${exam.subject}`, 50, y, 10);
  y -= 14;
  const scheme = getMarkingScheme(exam);
  const maxMarks = computeMaxMarks(scheme);
  const schemeSummary = scheme.length === 1 ? `Marks per question: ${scheme[0].marks}  |  Negative: ${scheme[0].negativeMarks}` : formatSchemeSummary(scheme);
  drawText(`Questions: ${exam.questionCount}  |  ${schemeSummary}  |  Max Marks: ${maxMarks}`, 50, y, 9, false, rgb(0.3,0.3,0.3));
  y -= 25;

  // Student info
  drawText("STUDENT REPORT", 50, y, 12, true, rgb(0.2,0.2,0.6));
  y -= 18;
  page.drawLine({ start: { x: 50, y }, end: { x: width - 50, y }, thickness: 1, color: rgb(0.8,0.8,0.8) });
  y -= 18;
  drawText(`Student: ${submission.studentName || "Unknown"}`, 50, y, 11, true);
  y -= 16;
  drawText(`Roll Number: ${submission.rollNumber || "-"}`, 50, y, 10);
  y -= 16;
  drawText(`Score: ${submission.score} / ${maxMarks}`, 50, y, 11, true);
  y -= 16;
  drawText(`Correct: ${submission.correct}  |  Incorrect: ${submission.incorrect}  |  Blank/Unattempted: ${submission.blank}`, 50, y, 10, false, rgb(0.3,0.3,0.3));
  y -= 24;

  // Table header
  drawText("QUESTION DETAILS", 50, y, 11, true);
  y -= 16;
  const colX = [50, 130, 230, 360, 470];
  const headers = ["Q No", "Student", "Correct", "Result", "Marks"];
  headers.forEach((h, i) => drawText(h, colX[i], y, 9, true, rgb(1,1,1)));
  // header bg
  page.drawRectangle({ x: 45, y: y - 6, width: width - 90, height: 18, color: rgb(0.2,0.2,0.6), opacity: 1 });
  headers.forEach((h, i) => drawText(h, colX[i], y, 9, true, rgb(1,1,1)));
  y -= 18;

  const details = submission.details || [];
  for (let idx = 0; idx < details.length; idx++) {
    if (y < 60) {
      page = pdfDoc.addPage([595, 842]);
      y = height - 50;
    }
    const d = details[idx];
    const rowColor = idx % 2 === 0 ? rgb(0.97,0.97,0.97) : rgb(1,1,1);
    page.drawRectangle({ x: 45, y: y - 4, width: width - 90, height: 16, color: rowColor });

    let resultColor = rgb(0,0,0);
    if (d.result === "Correct") resultColor = rgb(0,0.6,0);
    else if (d.result === "Incorrect") resultColor = rgb(0.8,0,0);
    else resultColor = rgb(0.5,0.5,0);

    drawText(String(d.question), colX[0], y, 9);
    drawText(d.studentAnswer, colX[1], y, 9);
    drawText(d.correctAnswer, colX[2], y, 9);
    page.drawText(d.result, { x: colX[3], y, size: 8, font, color: resultColor });
    drawText(String(d.marks), colX[4], y, 9);
    y -= 16;
  }

  y -= 20;
  if (y < 80) {
    page = pdfDoc.addPage([595,842]);
    y = height - 50;
  }
  drawText("Generated by OmiCheckr — Vision LLM Bubble Sheet Grader", 50, 40, 7, false, rgb(0.5,0.5,0.5));
  drawText(new Date().toLocaleString(), width - 180, 40, 7, false, rgb(0.5,0.5,0.5));

  return await pdfDoc.save();
}
